sanasa:
  url: http://www.sanasa.com.br/ura-quadrodeavisos/exibeResultado.asp
address:
  code: 3350063
users:
  email:
    - cardosounicamp@gmail.com
    - taisa881@gmail.com

mail_subject: Status do suprimento de água diário
mail_sender: cardosounicamp@gmail.com